In [1]:
import numpy as np
from implicit.als import AlternatingLeastSquares as ALS
from implicit.bpr import BayesianPersonalizedRanking as BPR
import scipy

In [2]:
R = scipy.sparse.csr_matrix(np.array([
    [0,3,2],
    [5,1,2],
    [4,2,1],
    [2,0,4],
]))

In [3]:
als_model = ALS(factors=2,regularization=0.01,iterations=10)
als_model.fit(R.T)

100%|██████████| 10/10 [00:00<00:00, 178.74it/s]


In [4]:
np.dot(als_model.user_factors,als_model.item_factors.T)

array([[0.28161323, 0.95638037, 0.96093124, 1.121579  ],
       [1.069851  , 0.82294357, 0.9350704 , 0.191945  ],
       [0.8057529 , 1.1520642 , 1.21855   , 0.9152018 ]], dtype=float32)

In [5]:
print('User factors')
print(als_model.user_factors)
print('\nitem factors')
print(als_model.item_factors.T)

User factors
[[ 2.5596156   2.9956737 ]
 [-0.16911875  1.3866044 ]
 [ 1.7463411   2.9371297 ]]

item factors
[[-0.6939295  -0.28086922 -0.3621319   0.24167417]
 [ 0.68692595  0.55923903  0.63019204  0.16790415]]
